### ISSUE TITLE
OSD fonts are black

### ISSUE THREAD

**Issue by synancia** [KissUltra/wiki#1]
Hey Kiss team,

In the beginnings the OSD Kiss Ultra V2 fonts were in white colour and suddenly they changed to black. Is there a way to change the fonts colour back to white? I tried to do factory reset but that did not help.

Cheers,
Markos

**Comment by KissUltra** [comment]
can you show the dvr how it looks? 
also can you show OSD -> Ultra setup screen?

**Comment by KissUltra** [comment]
also get on discord!

**Comment by synancia** [comment]
<img width="399" alt="OSD setup" src="https://github.com/KissUltra/wiki/assets/24797346/39e06b19-3ba7-45be-b9c0-1504d55d54b7">

Discord -> synancia26

DVR:

<img width="634" alt="dvr" src="https://github.com/KissUltra/wiki/assets/24797346/74c4e6c1-d4b4-4d4d-a2a7-ad40a9f323a7">

**Comment by KissUltra** [comment]
i ment how it looks ON TRHE DVR. :)

cant find you on discord, dm me, will sort you out.

**Comment by fedorcomander** [comment]
Link to discord u can find in the gui landing page :) green button :)

**Comment by synancia** [comment]
Haha I never used discord :) https://discord.gg/NpFyzRUS

**Comment by synancia** [comment]
I send you a request! Have a look :) Btw on the previous comment I added the dvr!

**Comment by KissUltra** [comment]
Black pixels could be damage in components or solder ball between switch chip pads. Need high res pictures of the parts that are close to FPV pads (video in/video out).

**Comment by KissUltra** [comment]
u can make OSD inverted and keep flying ;) Set black level to 200, and white level to 60 :) like TBS osd style :)

**Comment by KissUltra** [comment]
<img width="412" alt="Screenshot 2024-06-08 at 07 50 44" src="https://github.com/KissUltra/wiki/assets/86871477/88f75fab-d93a-41d0-a73f-81bd4dfa2699">

**Comment by synancia** [comment]
Thanks for the info! I tried that method (black level 200, and white level 60) and it didn't work. I will try to resolder the camera and the vtx on kiss ultra v2. Although, I checked the foxeer camera OSD and the OSD fonts are white..

**Comment by fedorcomander** [comment]
No mate, it’s not the camera not vtx. it’s a  SIGNAL level for white pixels. most likely some component knocked out. If you are in EU - i can fix it for you.

**Comment by synancia** [comment]
Oh okay, I understand. Here is my email -> Markos.charalambous26@gmail.com

**Comment by KissUltra** [comment]
If this method didnt work, most likely dac chip died.
