### ISSUE TITLE
Unable to select "5362" frequency in "vtx configuration"

### ISSUE THREAD

**Issue by GItHubUser-H2O** [KissUltra/wiki#2]
![屏幕截图 2024-06-08 202807](https://github.com/KissUltra/wiki/assets/60378792/c9ac0373-434f-4d90-8513-15cf583db4e4)
![屏幕截图 2024-06-08 202846](https://github.com/KissUltra/wiki/assets/60378792/2a459cdb-55a1-4717-af94-fade10086e8f)
My rush solo max supports "5362" frequency but I can't select "5362" on kiss gui

**Comment by KissUltra** [comment]
i support only official channels. ---Cheers,AlexOn 8 Jun 2024, at 14:37, GITHUB_User_h2o ***@***.***> wrote:﻿
2024-06-08.202807.png (view on web)
2024-06-08.202846.png (view on web)
My rush solo max supports "5362" frequency but I can't select "5362" on kiss gui

**Comment by GItHubUser-H2O** [comment]
Ok, I see, thanks for your reply
